apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jd1
  name: jd1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jd1
  strategy: 
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jd1
    spec:
      containers:
      - image: hbstarjason/jd-scripts:latest
        name: jd-scripts
        volumeMounts:
          - mountPath: /all
            name: jd1-env-all
      volumes:
        - name: jd1-env-all
          configMap:
            name: jd1-configmap-all
