name: 07hzh

on:
  workflow_dispatch: 
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]
  schedule:
    - cron:  44 1,14 * * *
      # 
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/
  #watch:
  #    types: started   

jobs:
  hzh:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Nodejs
      uses: actions/setup-node@v4
      with:
       pnode-version: '22.x'
    - run: |
       node -v
       node hzh.js
      env:
         hzh_url: ${{ secrets.HZH }}
      
    #- name: Install node
    #  run: |
    #    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
    #    source ~/.bashrc
        
    #    nvm use system
    #    npm uninstall -g a_module
        
    #    nvm install --lts
    #    nvm use --lts
    #    nvm install 22
        
        #sudo apt update && \
        #sudo apt install nodejs

        #curl -fsSL https://deb.nodesource.com/setup_22.x -o nodesource_setup.sh
        #sudo -E bash nodesource_setup.sh
        #curl -sL https://deb.nodesource.com/setup_22.x | sudo -E bash -
        #sudo apt update && sudo apt-get install -y nodejs
        
        #node -v
      
       
    #- name: Task
    #  run: |
    #   git clone https://github.com/hbstarjason2021/yangmao && cd yangmao/
    #   ls -l 
        
    #   nodejs hzh.js

    #  env: 
    #    hzh_url: ${{ secrets.HZH }}
