name: checkjs

on:
  workflow_dispatch: 
  schedule:
    - cron:  0 9,12,21 * * * 
      # 
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/
  #watch:
  #    types: started   

jobs:
  checkjs:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    #- uses: actions/checkout@v2
    
    - name: Checkjs
      run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         
         git clone https://github.com/ITdesk01/Checkjs.git /usr/share/Checkjs
         cd /usr/share/Checkjs && chmod 755 checkjs.sh
         bash checkjs.sh
         
         echo "==============================="
         ls -l git_log
         echo "==============================="
         current_time=$(date +"%Y-%m-%d-%k")
         echo ${current_time}
         git_log_timme=(date +"%Y-%m-%d")
         echo "==============================="
         cat git_log/${git_log_timme}.log
