name: checkjs

on:
  workflow_dispatch: 
  schedule:
    - cron:  0 10,16 * * * 
      # 
      # https://tool.lu/crontab/
      # https://datetime360.com/cn/utc-cst-china-time/
  #watch:
  #    types: started   

jobs:
  checkin:
    runs-on: ubuntu-latest
    #if: github.event.repository.owner.id == github.event.sender.id
    # https://p3terx.com/archives/github-actions-manual-trigger.html
    
    steps:
    #- uses: actions/checkout@v2
    
    - name: Checkjs
      run: |
         git clone https://github.com/ITdesk01/Checkjs.git /usr/share/Checkjs
         cd /usr/share/Checkjs && chmod 755 checkjs.sh
         bash checkjs.sh
         
         #cat 
