name: jd_all_task-new

on:  
  #push: # push触发
  #  branches: [ main ]
  workflow_dispatch: # 手动触发
  #schedule: # 计划任务触发
  #  - cron: '28 0-23/2 * * *' # cron表达式，Actions时区是UTC时间，所以要往前推8个小时(4-23)
    
jobs:
  jd_all_task:
    runs-on: ubuntu-latest    
    steps:   
    # 检出
    #- name: Checkout
    #  uses: actions/checkout@v2
      
    # 设置服务器时区为东八区 
    - name: Set time zone
      run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         current_time=$(date +"%Y-%m-%d-%k")
         echo ${current_time}
    - name: Run jd_all_task
      run: |
         #timedatectl set-timezone 'Asia/Shanghai'
         
         #docker info
         docker-compose version
         git clone https://github.com/hbstarjason2021/jd-scripts-docker && cd jd-scripts-docker
         docker pull hbstarjason/jd-scripts
         
         #docker pull registry.cn-beijing.aliyuncs.com/hbstarjason/jd-scripts@sha256:acf281ad4374d6cac315fa76f78c1d5bddc23980627b5c7ebf7e62745491c191
         #docker tag registry.cn-beijing.aliyuncs.com/hbstarjason/jd-scripts@sha256:acf281ad4374d6cac315fa76f78c1d5bddc23980627b5c7ebf7e62745491c191 hbstarjason/jd-scripts
         
         sed -i '2s/pt_key=/pt_key="${{secrets.KEY1}}"/' env/env1 
         #sed -i '3s/pt_pin=/pt_pin="${{secrets.PIN1}}"/' env/env1
         sed -i '3s/pt_pin=/pt_pin=jd_709c349f13b51/' env/env1
 
         sed -i '2s/pt_key=/pt_key="${{secrets.KEY4}}"/' env/env4 
         sed -i '3s/pt_pin=/pt_pin=starjason/' env/env4
         
         sed -i '2s/pt_key=/pt_key="${{secrets.KEY2}}"/' env/env2 
         sed -i '3s/pt_pin=/pt_pin=yuxiachenqi/' env/env2
         
         sed -i '2s/pt_key=/pt_key="${{secrets.KEY3}}"/' env/env3 
         sed -i '3s/pt_pin=/pt_pin=fu5520jing/' env/env3
         
         
         docker-compose up --no-build --force-recreate --detach jd1
         docker-compose up --no-build --force-recreate --detach jd4
         docker-compose up --no-build --force-recreate --detach jd2
         docker-compose up --no-build --force-recreate --detach jd3
               
         cp 01run.sh 02run.sh &&  sed -i "s/jd1/jd2/g"  02run.sh
         cp 01run.sh 03run.sh &&  sed -i "s/jd1/jd3/g"  03run.sh 
         cp 01run.sh 04run.sh &&  sed -i "s/jd1/jd4/g"  04run.sh

         
         docker images 
         docker ps 
         
         ## docker exec jd1 bash -c 'set -o allexport; source /all; source /env; source /jd-scripts-docker/resolve.sh; cd /scripts; yxyPhone="${{secrets.YXYPHONE}}";  node yxyapp.js'
         
         #docker exec jd1 bash -c 'set -o allexport; source /all; source /env; source /jd-scripts-docker/resolve.sh; cd /scripts; node jd_bean_change_ccwav.js'

         ###### 
         ls -l |grep "run.sh"
         
         #sh 01run.sh
         #sh 02run.sh
         #sh 03run.sh
         #sh 04run.sh
         
  jd_run_1:  
    runs-on: ubuntu-latest
    #needs: jd_all_task
    steps:
    - name: Run jd_run_1
      run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         current_time=$(date +"%Y-%m-%d-%k")
         echo ${current_time}      
         #timedatectl set-timezone 'Asia/Shanghai'
         
         sleep $(shuf -i 10-30 -n 1)
         
         #docker info
         docker-compose version
         git clone https://github.com/hbstarjason2021/jd-scripts-docker && cd jd-scripts-docker
         docker pull hbstarjason/jd-scripts
         
         docker images 
             
  jd_run_2:  
    runs-on: ubuntu-latest
    #needs: jd_all_task
    steps:
    - name: Run jd_run_2
      run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         current_time=$(date +"%Y-%m-%d-%k")
         echo ${current_time}
         #timedatectl set-timezone 'Asia/Shanghai'
         
         sleep $(shuf -i 10-30 -n 1)
         
         #docker info
         docker-compose version
         git clone https://github.com/hbstarjason2021/jd-scripts-docker && cd jd-scripts-docker
         docker pull hbstarjason/jd-scripts
         
         docker images
 
  jd_run_3:  
    runs-on: ubuntu-latest
    #needs: jd_all_task
    steps:
    - name: Run jd_run_3
      run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         current_time=$(date +"%Y-%m-%d-%k")
         echo ${current_time}
         #timedatectl set-timezone 'Asia/Shanghai'
         
         sleep $(shuf -i 10-30 -n 1)
         
         #docker info
         docker-compose version
         git clone https://github.com/hbstarjason2021/jd-scripts-docker && cd jd-scripts-docker
         docker pull hbstarjason/jd-scripts
         
         docker images

  jd_run_4:  
    runs-on: ubuntu-latest
    #needs: jd_all_task
    steps:
    - name: Run jd_run_4
      run: |
         sudo timedatectl set-timezone 'Asia/Shanghai'
         current_time=$(date +"%Y-%m-%d-%k")
         echo ${current_time}
         #timedatectl set-timezone 'Asia/Shanghai'
         
         sleep $(shuf -i 10-30 -n 1)
         
         #docker info
         docker-compose version
         git clone https://github.com/hbstarjason2021/jd-scripts-docker && cd jd-scripts-docker
         docker pull hbstarjason/jd-scripts
         
         docker images
