name: jd
on:
  workflow_dispatch:
  schedule:
    - cron: 5 */2 * * *
  watch:
    types: started
jobs:
  build:
    runs-on: Ubuntu-20.04  
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt install rename -y
        sudo npm install -g typescript
    - name: down
      run: |
        echo "========= 开始下载JDHelloWorld的脚本 ========="
        git clone -b main https://github.com/JDHelloWorld/jd_scripts.git ./JDHelloWorld
        ## mv ./JDHelloWorld/githubAction.md ./githubAction.md
        ## mv ./JDHelloWorld/sendNotify.js ./sendNotify.js
        ## mv ./JDHelloWorld/utils/*.json ./utils/
        ## mv ./JDHelloWorld/utils/*.js ./utils/
        ## mv ./JDHelloWorld/utils/*.ts ./utils/
        cd ./JDHelloWorld
        echo "========= 开始安装依赖 ========="
        sudo npm install
        echo "========= 开始转换JDHelloWorld的ts ========="
        #tsc ./*.ts
        
        tsc jx_nnfls.ts
        #tsc jd_tewu.ts
        tsc TS_USER_AGENTS.ts
        tsc jd_jxmc.ts
        #tsc jd_xtg.ts
        tsc jd_cfd.ts
        tsc jd_cfd_shell.ts
        tsc jd_fruit_moreTask.ts
        tsc jd_mofang.ts
        #tsc jd_speed_redEnvelope.ts
        tsc jx_box.ts
        #tsc jd_88hb.ts
        tsc jd_bean_box.ts
        tsc jd_jxmc.ts
        tsc jd_health.ts
        tsc jd_tiger.ts

        cp ./jx_nnfls.js ../
        #cp ./jd_tewu.js ../
        cp ./TS_USER_AGENTS.js ../
        cp ./jd_jxmc.js ../
        #cp ./jd_xtg.js ../
        cp ./jd_cfd.js ../
        cp ./jd_cfd_shell.js ../
        cp ./jd_fruit_moreTask.js ../
        cp ./jd_mofang.js ../
        #cp ./jd_speed_redEnvelope.js ../
        cp ./jx_box.js ../
        #cp ./jd_88hb.js ../
        cp ./jd_bean_box.js ../
        cp ./jd_jxmc.js ../
        cp ./jd_health.js ../
        cp ./jd_tiger.js ../

        #cp -f ./JDHelloWorld/*_*.js ./
        #cp -f ./JDHelloWorld/*_*.ts ./ts
        rm -rf ./JDHelloWorld
        
        echo "========= 转换完成 ========="
    - name: 'Commit Files'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am 'robot'
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: main
