name: jd
on:
  workflow_dispatch:
  schedule:
    - cron: 5 */2 * * *
  watch:
    types: started
jobs:
  build:
    runs-on: Ubuntu-20.04  
    steps:
    - uses: actions/checkout@v2
    - name: Install build dependencies
      run: |
        sudo apt install rename -y
        sudo npm install -g typescript
    - name: down
      run: |
        echo "========= 开始下载JDHelloWorld的脚本 ========="
        git clone -b main https://github.com/JDHelloWorld/jd_scripts.git ./JDHelloWorld
        ## mv ./JDHelloWorld/githubAction.md ./githubAction.md
        ## mv ./JDHelloWorld/sendNotify.js ./sendNotify.js
        ## mv ./JDHelloWorld/utils/*.json ./utils/
        ## mv ./JDHelloWorld/utils/*.js ./utils/
        ## mv ./JDHelloWorld/utils/*.ts ./utils/
        cd ./JDHelloWorld
        echo "========= 开始安装依赖 ========="
        sudo npm install
        echo "========= 开始转换JDHelloWorld的ts ========="
        #tsc ./*.ts
        
        tsc jx_nnfls.ts
        tsc jd_homepageTW.ts
        tsc TS_USER_AGENTS.ts

        cp ./jx_nnfls.js ../
        cp ./jd_homepageTW.js ../
        cp ./TS_USER_AGENTS.js ../

        #cp -f ./JDHelloWorld/*_*.js ./
        #cp -f ./JDHelloWorld/*_*.ts ./ts
        rm -rf ./JDHelloWorld
        
    - name: 'Commit Files'
      id: commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || git commit -am 'robot'
    - name: Push Dust
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        branch: main
